// =====================================================================
//  "Turon Ilm Xazinasi" maktabining boshlang'ich ro'yxati.
//
//  Manba — maktabdan kelgan to'lov ro'yxati (2026-08-27). U qo'lda
//  yuritilgan va shu holicha ko'chirilgan: hech qanday ism tuzatilmagan,
//  hech narsa qo'shilmagan. Tozalash `import-turon.mjs` da bajariladi
//  va u qilgan har bir o'zgarish hisobotda ko'rinadi.
//
//  NARX MING SO'MDA: 850 → 850 000 so'm. Buni Farhodjon tasdiqladi.
//
//  `null` narx — ro'yxatda "--------" turgan, ya'ni summa hali
//  belgilanmagan. Bunday o'quvchi shartnomasiz qo'shiladi.
// =====================================================================

/** To'lov ro'yxati: har guruh va undagi o'quvchilar. */
export const GROUPS = [
  {
    name: '1-A', grade: 1, lang: "O'zbek tili",
    students: [
      ['Adhamova Hadija', 850],
      ['Masodiqov Muhammadyusuf', 850],
      ['Usmonbekov Muhammadsolih', 850],
      ['Toirov Abdulloh', 850],
      ['Muhitdinov Holid', 850],
      ['Hayitboyev Muhammadsolih', 850],
      ['Zufarov Muhammad', 1200],
      ['Kamalova Oyishaxon', 850],
      ['Solijonov Muhammadamin', 1200],
      ['Serobjonova Mumtozbegim', 1200],
      ['Bahtiyorjonova Amiraxon', 1200],
      ['Ibragimov Mustafo', 1200],
      ['Umaraliyeva Bibixojar', 850],
      ['Yusupova Hadicha', 1000],
      ['Qahramonjonov Muhammadjon', 850],
      ['SHuhratjonov Muhammadsolih', 1200],
      ['Rustamjonova Imonaxon', 850],
      ['Axrorov Muhammadali', 1200],
      ['Islomjonov Muhammadrasul', 1000],
      ['Rahmonjonov Bilol', 850],
      ['Azimhadjayev Ismoil', 850],
      ['Solihadjayeva Hadicha', 1200],
    ],
  },
  {
    name: '1-B', grade: 1, lang: "O'zbek tili",
    students: [
      ['Islomjonov Abdulloh', 850],
      ['Nematullayeva Maryamxon', 1200],
      ['Mamajonov Mirakbar', 850],
      ['Muhtorova Farzona', 1200],
      ["Sayidqosimova Dlafro'z", 1200],
      ['Masodiqova Oyishaxon', 850],
      ['Kamalova Mohina', 1000],
      ["Meliqo'ziyeva Ezoza", 1000],
      ['Dilshodov Muhammadrizo', 850],
      ['Anvarov Muhammadsodiq', 850],
      ["Ne'matov Nurmuhammad", 850],
      ['Rahmonjonova Soliha', 1200],
      ['Donyorjonova Soliha', 850],
      ['Muzaffarjonova Mumtozbegim', 850],
      ['Tillabobayev Mustafo', 850],
      ['Rahimov Abdullajon', 1200],
      ['Xayrullayev M Mustafo', 1000],
    ],
  },
  {
    name: '1-V', grade: 1, lang: 'Rus tili',
    students: [
      ['SHokirova Solixabonu', 1500],
      ['Akbarov Hasan', 1600],
      ['Akbarov Husan', 1600],
      ['Rahmonjonov Sarvar', 1700],
      ['Usmonova Sakina', 1600],
      ['Axmedov Muhammadrizo', 1700],
      ['Bahodirov Durbek', 1700],
      ['SHavkatov Kamolxon', 1700],
      ['Muhammadjonov Islombek', 1500],
      ['SHarifjonov Mustafo', 1600],
      ['SHarifjonov Umarxon', 1600],
      ['Qahramonjonov Abubakir', 1700],
    ],
  },
  {
    name: '2-B', grade: 2, lang: null,
    students: [
      ['Turakulov Muhammadmustafo', 1700],
      ['Umarov Abubakr', 1700],
      ['Jalilova Zinnurabonu', 1700],
      ['Muxtorova Feruzaxon', 1600],
      ['Akramov Muhammadsolih', 1600],
      ['Xayrullayeva Imronaxon', 1700],
      ["G'ayratov Muhammadmustafo", 1700],
      ['Sharipova Hadichabonu', 1700],
      ['Ibragimov Murodbek', 1700],
      ["Nu'monjonova Yasina", 1700],
      ['Maxsudjonov Behruzbek', 1700],
      ['Xakimov Muhammadyusuf', 1700],
      ['Komilova Marziyaxon', 1700],
      ['Odilbekov Sarvar', 1500],
      ['Abduraximova Asmoxon', 1700],
      ['Inomova SHukronaxon', 1700],
      ["G'aniyev Musab", null],
      ['Munavvarov Nurmuhammad', 1500],
      ['Nabiyev Anasxon', 1700],
    ],
  },
  {
    name: '3-A', grade: 3, lang: null,
    students: [
      ['Abdurashidova Hadichaxon', 1700],
      ['Karimnazarov Muhammadamin', 1600],
      ['Salixadjayev Salohiddin', 1700],
      ['Bahtiyorjonova Imonaxon', 1700],
      ['Karabayev Muhammadamirxon', 1700],
      ["Aliev Abdumo'min", 1700],
      ['Ahmedova Marhamatxon', 1700],
      ["Mo'ydinov Nursultonxon", 1700],
      ['Bahodirova Asmo', null],
      ['Jengiz Emirxan', 1700],
      ["Numanova Mohizo'zaxon", null],
      ['Rustamov Abdulloh', 1700],
      ['Muhammadiyev Ali', 1700],
      ['Umarova Hadichaxon', 1600],
      ['Rustamova Mumtozbegim', 1400],
      ['Abdurahimov Muhammadsodiq', 1700],
    ],
  },
  {
    name: '3-B', grade: 3, lang: null,
    students: [
      ['Akmaljonov Zubayr', 1700],
      ['Ahmedov Hojiakbar', 1500],
      ['Hakimjonova Hadichaxon', 1700],
      ['Usmonova Hadicha', 1700],
      ['Adilova Asalbibi', 1700],
      ['Bahromova Dilsorabegim', 1700],
      ['Varisov Sultonmurod', 1700],
      ["O'tkirjonov Sayidalixon", 1550],
      ['Islomova Soliha', 1700],
      ['Maqsudjonov Mahmudjon', 1700],
      ['Nizomiddinov Muhammadsolih', 1600],
      ["Po'latov Mahmudjon", 1700],
      ['Rashidxonov Raxmatxon', 1700],
      ['Abdusattorov Abdulloh', 1700],
      ['Yakubov Mustafo', 1450],
    ],
  },
  {
    name: '4-A', grade: 4, lang: null,
    students: [
      ['Aliev Abdulaziz', 1700],
      ['Alijonov Alijon', 1600],
      ['Marupov Mustafo', 1600],
      ['Sharipova Parizodabegim', 1700],
      ['Qoraboeva Muruvvatxon', 1300],
      ['Ahmedov Ahmadjon', 1700],
      ['Muhammadjonova Gulirano', 1700],
      ['Foziljonova Mohizodaxon', 1600],
      ['Ikromov Muhamadamin', 1600],
      ['Izzatullaeva Muzifaxon', 1600],
      ['Karimnazarova Ominaxon', 1600],
      ['Mirzayunusova Samiraxon', 1700],
      ['Mirfayozov Ismoil', 1700],
      ["Fozilov Ulug'bek", 1500],
      ['Sharipova Zinnura', null],
      ['Rustamova Solihabonu', 1400],
      ['Xamidova Oishaxon', 1700],
      ['Aminova Solihanur', 1600],
    ],
  },
  {
    name: '4-B', grade: 4, lang: null,
    students: [
      ['Karimova Bibisora', 1500],
      ['Mahkamov Ali', 1600],
      ['Muhammedjanov Otabek', 1450],
      ['Abdullayev Abdurashid', 1300],
      ["Ma'murov Muhammadumar", 1800],
      ['Mamatqulov Temur', 1600],
      ['Haytmatova Yasinaxon', 1600],
      ['Kariev Muhammadmustafo', 1700],
    ],
  },
  {
    name: '5-A', grade: 5, lang: null,
    students: [
      ['Valixonov SHukurxon', 1600],
      ['Bahtiyorov Abdurahmon', 1700],
      ['Rahmonov Ikromjon', 1700],
      ['Muhammadjonov Muhammadsodiq', 1700],
      ["Mo'ydinov To'lqinjon", 1700],
      ['Mamatqulov Diyor', 1700],
      ["Muhammadjonov Behro'zbek", 1700],
      ['Hasanov Imronbek', 1700],
    ],
  },
  {
    name: '6-A', grade: 6, lang: null,
    students: [
      ['Ahmedova Osiyo', 1600],
      ['Usmonov Sayidumar', 1700],
      ['Ilyosova Munisa', 1600],
      ['Hakimov Islombek', 1600],
      ['Qurbonjonov Imronbek', 1700],
    ],
  },
  {
    name: '7-A', grade: 7, lang: null,
    students: [
      ['Abdullaeva Mubina', 1700],
      ['Turdaliev Omar', 1700],
      ["O'tkirjonov Sayidazimxon", 1550],
      ['Abdurashidov Anasxon', 1700],
      ['Ilhomova Zaynabbegim', 1700],
      ['Abdullayeva Olimaxon', 1700],
      ['Odilov Muhammadjon', null],
      ['Fozilova Sevinch', 1500],
      ['Subxonova Hosiyatxon', 1600],
    ],
  },
  {
    name: '9-A', grade: 9, lang: null,
    students: [
      ['Abdullayeva Zulfiya', 1700],
      ['Abdullayev Abubakir', 1100],
      ['Ummataliev Muhammadali', 1700],
      ['Nosirov Muhtorjon', 1700],
      ['Subxonova Kumushbibi', 1600],
      ['Nazirov Nozimjon', 1700],
    ],
  },
  {
    name: "Bog'cha-1", grade: 0, lang: null,
    students: [
      ['Abdumuhtorov Mirzohidjon', 1200],
      ["A'zamova Sumayya", 1200],
      ['Muhammadzokirov Msolih', 1200],
      ['Farhodjonov Abubakir', 1200],
      ['Obidjonova Muslimaxon', 1200],
      ['Nuriddinov Ziyoviddin', 1200],
      ['Muhammadjonov Ibrohimjon', 1200],
      ["Do'smatova Fotimaxon", 1200],
      ["Ho'jamurodov Muhammadyusuf", 1200],
      ["G'ayratova Mohizoda", null],
      ["Ma'murov Muhammadziyo", 1200],
      ['Madaminova Marziyaxon', 1200],
      ["G'ayratjonova Soliha", 1200],
      ["Anvarjonov Xo'ja", 1200],
      ["G'aniyeva Muslimaxon", null],
      ['Bahodirova Muslima', null],
      ['Xaydarov Sayitazim', 1200],
      ['Xaydarova Zaynab', 1200],
      ['Sayidaxmedov Muhammadumar', 1200],
    ],
  },
  {
    name: "Bog'cha-2", grade: 0, lang: null,
    students: [
      ['Nuriddinov Muhammadrizo', 1200],
      ['Ibragimova Imonaxon', 1000],
      ['Xotamqulov Zubayr', 1000],
      ['Adhamov Muhammadisxoq', 1200],
      ['Hadjayev Umarxon', 1000],
      ['Anvarov M Umarxon', null],
      ['Akbarov Abdulloh', 1000],
      ['SHokirov Muhammadamin', 1000],
      ['SHokirjonov Muhammad Yusuf', 500],
      ["G'ayratjonova Honzoda", null],
      ['Haydaraliyeva Nuriya', 1000],
      ['Karimnazarova Oyishaxon', 1000],
      ['Subxonov Muhammadali', 1000],
      ['Muhtorov Muhsinjon', 1000],
      ['Umitjonov Muhammadyusuf', 1000],
    ],
  },
  {
    name: 'Lager', grade: null, lang: null,
    students: [
      ['Muhtorova Feruza', 1200],
      ['Ibrohimova Azizaxon', 1200],
      ['Muhammedova Oyazimxon', 1200],
      ['Muhammadiyev Ali', 1200],
      ['Ahmedov Azizxon', 1200],
      ["Ma'murov Ma'murjon", 1200],
      ['Umarov Abubakir', 1200],
      ['Madaminov Umarxon', 1200],
      ['Subxonova Yasmina', 1000],
      ['Kamalova SHahina', 1200],
      ['Adhamova Nasiba', 1200],
      ["G'ayratov Muhammadrizo", 1200],
      ['Adxamova Nasiba', 1200],
      ['Abdurahimova Asmo', 850],
      ['Qodirova Imrona', 1200],
      ['Zokorov Abdurahmon', 1200],
      ['Artiqova Muzdalifa', 1200],
    ],
  },
];

/**
 *  Rasmiy ro'yxat — to'liq ism-sharif bilan.
 *
 *  Bu AYNAN o'sha bolalar, faqat to'liq yozilgan (Farhodjon
 *  tasdiqladi). Shuning uchun ular yangi o'quvchi sifatida
 *  qo'shilmaydi: mos kelgani topilsa ismi to'ldiriladi, topilmasa
 *  yangi o'quvchi bo'lib qo'shiladi.
 */
export const REGISTER = [
  ['1-A', "Azimxodjayev Ismoilxon Akmal o'g'li"],
  ['1-A', "G'oziyeva Soliha Olimjon qizi"],
  ['1-A', 'Rustamjonova Imonaxon Dostonjon qizi'],
  ['1-A', 'Solixodjayeva Hadichaxon Jalolxon qizi'],
  ['1-A', 'Ummataliyeva Zaynabxon Raximjon qizi'],
  ['1-A', 'Baxtiyorjonov Amiraxon Bekzodjon qizi'],
  ['1-A', "Toirov Abdulloh Baxodir o'g'li"],
  ['1-A', "Islamkulov Muhammadrasul Davronbek o'g'li"],
  ['1-A', "Usmonbekov Muhammadsolih Muzaffarxon o'g'li"],
  ['1-A', 'Ilhomjonova Mohinur Oxinjon qizi'],
  ['1-A', "Shuxratjonov Muhammadsolih Xabibulloxon o'g'li"],
  ['1-A', "Umarov Muhammadmustafo Mumin o'g'li"],
  ['1-A', "Adxamov Muhammadloiq Ilyos o'g'li"],
  ['1-A', 'Serobjonova Mumtozbegim Nurmuxammadjon qizi'],

  ['1-B', 'Raximova Oishaxon Nuriddin qizi'],
  ['1-B', "Baxromjonov Bilol Bunyodjon o'g'li"],
  ['1-B', 'Narimanova Soliha Nodir qizi'],
  ['1-B', 'Muhamedjanov Habibulloh'],
  ['1-B', "Axrorov Muhammadali Baxtiyor o'g'li"],
  ['1-B', "Kurbonjonov Muhammadyusuf Kamoljon o'g'li"],
  ['1-B', 'Umaraliyeva Bibihojar Muhammadamin qizi'],
  ['1-B', 'Abdunosirova Azmiyaxon Abdulbori qizi'],
  ['1-B', 'Kadirova Afruzaxon Axror qizi'],
  ['1-B', "Masadikov Muhammadyusuf Rustamjon o'g'li"],
  ['1-B', "Turdialiyev Haled Mohammed o'g'li"],
  ['1-B', "Bulbul Muhammad Amir Aslan o'g'li"],
  ['1-B', 'Axrarova Mabrukaxon Jahongir qizi'],
  ['1-B', "Solijonov Muhammadamin Abbosxon o'g'li"],

  ['1-V', "Islomjonov Abdulloh Iqboljon o'g'li"],
  ['1-V', 'Xalilov Muhammadyusufxon Muxamm'],
  ['1-V', 'Muzaffarjonova Mumtozbegim Murtozoxon qizi'],
  ['1-V', 'Karimov Muhammad Yusuf'],
  ['1-V', 'Saliyeva Zinnuraxon Abrorjon qizi'],
  ['1-V', 'Doniyorjonova Solihabonu Abdulaziz qizi'],
  ['1-V', 'Muxtorova Farzonaxon Muzaffarjonovna'],
  ['1-V', "Kariyev Muhammad Yusuf Raufjon o'g'li"],
  ['1-V', "Raximov Abdullajon Davronbek o'g'li"],
  ['1-V', "Xayrulloyev Muhammadmustafo Xabibullo o'g'li"],
  ['1-V', 'Raxmonjonova Solihabonu Sarvarbek qizi'],
  ['1-V', 'Saidqosimova Dilafruzxon Iqboljon qizi'],
  ['1-V', 'Dilshodov Muhammadrizo Davronovich'],
  ['1-V', 'Mamajonov Mirakbar Miraxmadjonovich'],
  ['1-V', "Ne'matulloyeva Maryamxon Ziyodullo qizi"],
  ['1-V', 'Abdirimova Billura Ergash qizi'],
  ['1-V', 'Kadirova Samiyaxon Farxod qizi'],
  ['1-V', 'Negmatov Nurmuhammad Nazrullayevich'],
  ['1-V', 'Abdurashidova Ominaxon Azamat qizi'],
];
